# Generated by Django 3.2.19 on 2023-05-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0006_auto_20230530_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[("Kid's Wear", "Kid's Wear"), ("Men's Wear", "Men's Wear"), ("Women's Wear", "Women's Wear")], default="Men's Wear", max_length=200),
        ),
    ]
