# Generated by Django 3.2.19 on 2023-05-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0007_product_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[("Kid's Wear", "Kid's Wear"), ("Men's Wear", "Men's Wear"), ("Women's Wear", "Women's Wear"), ('Others', 'Others')], default="Men's Wear", max_length=200),
        ),
    ]
