# Generated by Django 3.2.19 on 2024-04-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0011_auto_20240328_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='instock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
