# Generated by Django 3.2.19 on 2024-04-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0012_size_instock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='instock',
        ),
        migrations.CreateModel(
            name='ProductSizeStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('instock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopapp.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopapp.size')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
