# Generated by Django 3.2.19 on 2024-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0013_auto_20240428_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='shortname',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
