# Generated by Django 3.2.19 on 2024-05-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0014_size_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='eshopapp.Size'),
        ),
    ]
